- hosts: wp_hosts
  vars_files:
    - vars.yaml
  vars:
    username: "{{ remote_web_user.name }}"
    authorized_key: "{{ remote_web_user.authorized_key }}"

    wordpress_path: "/var/www/{{ domain.url }}"
    execution_group: nginx
  become: true
  gather_facts: true
  remote_user: "{{ remote_sudo_user.name }}"
  roles:
    - update-system
    - install-common-packages
    - configure-firewall
    - create-user
    - geerlingguy.swap
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.repo-remi
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.redis
    - install-wp-cli
    - install-wordpress
