---
roles:
- name: geerlingguy.certbot
- name: geerlingguy.mysql
- name: geerlingguy.nginx
- name: geerlingguy.php
- name: geerlingguy.php-versions
- name: geerlingguy.redis
- name: geerlingguy.repo-remi
