- name: Ensure wheel group is created
  ansible.builtin.group:
    name: wheel
    state: present

- name: Add user to wheel group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel

- name: Allow paswordless login
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
