- name: Ensure wheel group is created
  ansible.builtin.group:
    name: wheel
    state: present

- name: Add remote sudo user 
  ansible.builtin.user:
    name: "{{ remote_sudo_user.name }}"
    shell: /bin/bash
    groups: wheel
    append: false
    create_home: true

- name: Allow paswordless login
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: Add authorized key
  ansible.posix.authorized_key:
    user: "{{ remote_sudo_user.name }}"
    key: "{{ remote_sudo_user.authorized_key }}"
    state: present
