---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - curl
      - fail2ban
      - git
      - htop
      - iotop
      - ncdu
      - ufw
      - unzip
      - zip
    state: latest
